name: ktlint

on:
  push:
    branches:
      - "*"
    paths:
      - "**/*.kt"
      - ".github/workflows/ktlinter.yml"
  pull_request:
    branches:
      - "*"
    paths:
      - "**/*.kt"
      - ".github/workflows/ktlinter.yml"

 jobs:
   ktlint:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: "ktlint"
         uses: "vroy/gha-kotlin-linter@v2"
